# Node config
node.ip = 127.0.0.1
node.port = 8001
node.tag = xdagj-node-1
node.maxInboundConnectionsPerIp = 8
node.whiteIPs = ["127.0.0.1:8001", "127.0.0.1:8002"]
node.generate.block.enable = true

# Node transaction history config
node.transaction.history.enable = false

# HTTP API Config
rpc.http.enabled = true
rpc.http.host = 127.0.0.1
rpc.http.port = 10001

# Randomx Config
randomx.flags.fullmem = false
